sudo: false
language: ruby
rvm:
  - 2.2.4
  - 2.3.3

install:
  - gem install bundler -v 1.16.0
  - bundle install --retry=3

script:
  - bundle exec rspec
  - bundle exec rubocop -R lib spec --format simple

addons:
    code_climate:
        repo_token: 5d3255ea9afc89e8f488f92dae45bc9d2fbe29fc27ade6fbcac348e24d51998c
